FROM golang:1.16.5-alpine3.13 as goBuilder
RUN apk add --no-cache bash
RUN mkdir -p /schedule-maker-build
WORKDIR /schedule-maker-build
COPY . .
RUN /bin/bash -c 'if [ ! -e ".env" ]; then  echo "env file not found" ;  exit 1  ; else echo "check env file success" ; exit 0; fi '
WORKDIR /schedule-maker-build/app/console/schedule_maker
RUN go build -o girlfriend-gift-schedule-maker

FROM alpine:latest
RUN apk add tzdata
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN mkdir -p /schedule-maker-app
WORKDIR /schedule-maker-app
COPY --from=goBuilder /schedule-maker-build/app/console/schedule_maker/girlfriend-gift-schedule-maker .
COPY --from=goBuilder /schedule-maker-build/.env .
ENTRYPOINT ["./girlfriend-gift-schedule-maker"]
