FROM golang:1.16.5-alpine3.13 as goBuilder
RUN apk add --no-cache bash
RUN mkdir -p /server
WORKDIR /server
COPY . .
RUN /bin/bash -c 'if [ ! -e ".env" ]; then  echo "env file not found" ;  exit 1  ; else echo "check env file success" ; exit 0; fi '
RUN go build -o girlfriend-gift-server

FROM alpine:latest
RUN apk add tzdata
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN mkdir -p /server-app
WORKDIR /server-app
COPY --from=goBuilder /server/girlfriend-gift-server .
COPY --from=goBuilder /server/.env .
ENTRYPOINT ["./girlfriend-gift-server"]
